baseurl = "https://www.eclipse.org/"
DefaultContentLanguage = "en"
title = "The Community for Open Innovation and Collaboration"
theme = "eclipsefdn-hugo-solstice-theme"
metaDataFormat = "yaml"
disableKinds = []
themesDir = "node_modules/"
enableRobotsTXT = true
pluralizeListTitles = false

[Params]
  google_tag_manager = "GTM-5WLCZXC"
  description = "The Eclipse Foundation provides our global community of individuals and organizations with a mature, scalable, and business-friendly environment for open source software collaboration and innovation."
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["eclipse", "project", "plug-ins", "plugins", "java", "ide", "swt", "refactoring", "free java ide", "tools", "platform", "open source", "development environment", "development", "ide"]
  news_count = 3
  featured_content_publish_target = "eclipse_org"
  styles = "css/styles.css"
  gcse = "011805775785170369411:p3ec0igo0qq"
  js = "js/solstice.js"
  header_wrapper_class = "header-wrapper header-default-bg-img featured-jumbotron-bottom-shape"
  call_for_action_text = "Download"
  call_for_action_url = "/download/"
  call_for_action_icon = "fa-download"
#  logo = ""
#  favicon = ""
#  share_img = ""
#  logo_width = ""
#  header_left_classes = ""
#  main_menu_wrapper_classes = "col-sm-17 margin-top-25"
#  projects_working_group = ""

  
[taxonomies]
  category = "categories"
  tag = "tags"
  membership_level = "membership_levels"
  participation_level = "participation_levels"

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "ECDTools"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 1
    
[[menu.main]]
    name = "Working Groups"
    url = "/org/workinggroups"
    weight = 2

[[menu.main]]
    name = "Members"
    url = "/membership"
    weight = 3
